### ISSUE TITLE
Crashlytics and Fabric update

### ISSUE THREAD

**Issue by pankkor** [lmirosevic/GBAnalytics#2]
Crashlytics has been updated. Now there is Fabric + different kits (one of which is crashlytics kit).
Maybe we should remove crashlytics from GBAnalytics? It doesn't support events anyway and it's initialisation interferes with other kits that you may want to use in your app (like mopub kit or twitter kit).

Typical crashlytics initialisation code looks like this now:
`[Fabric with:@[TwitterKit, CrashlyticsKit, MoPubKit]]`
This is it. APIKey is provided through .run script

From my pov it's easier to remove crashlytics as there is no benefit in supporting it with GBAnalytics.

**Comment by lmirosevic** [comment]
https://github.com/lmirosevic/GBAnalytics/releases/tag/2.10.0 adds support for using the new Crashlytics SDK via Fabric, while maintaining backwards compatibility.
